Interactive list functionality
mahdimahdawi/To-Do-List pull request #4
Opened 2022-08-18 13:49 UTC by mahdimahdawi

**This PR contain:**
- Implemented JavaScript modules to the project.
- Added event listener to checkbox for each list item and update the completed file as true.
- Implement functionality to item lists that are mark as completed.
- - Store the updating status to local storage.

2022-08-18 14:11 UTC, vechicin requested changes
# Hi @mahdimahdawi ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good job implementing most of the required features for this milestone!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 14:11 UTC, vechicin commented on src/list.js
>  import 'lodash';
Please do not disable ESLint rules.

2022-08-18 14:11 UTC, vechicin commented on modules/makeComplete.js
> +/* eslint-disable */
Please do not disable ESLint rules.

2022-08-18 14:11 UTC, vechicin commented on modules/clearComplete.js
> +/* eslint-disable */
Please do not disable ESLint rules.

2022-08-18 14:11 UTC, vechicin commented on src/list.js
> +  // document.querySelector('todo-list').innerHTML = '';
Please remove this line of commented code to keep a cleaner codebase.

2022-08-18 14:11 UTC, vechicin commented on src/list.js
> +    })
Please make sure you make the `completed` styling persist even after page refresh.

<img width="794" alt="Screen Shot 2022-08-18 at 9 09 31" src="https://user-images.githubusercontent.com/82426682/185415956-38c331be-0ad3-4d64-9a4d-187f1943c477.png">

As you can see, the task is marked as `completed` but the styling doesn't reflect it. Please fix it.

2022-08-19 06:29 UTC, mahdimahdawi commented
**Fix Required Changes:**
- - After refresh the page the checkbox for completed task is stay check.
- Fixed linter Error.
- Clean dead code from project.

2022-08-19 06:36 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @mahdimahdawi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The PR title and description looks professional✔️
- No linter errors✔️
- You did well to make the changes requested by the previous reviewer✔️


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 09:33 UTC, merged